another try

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -33,3 +33,12 @@ jobs:
           cache: "npm"
       - run: npm ci
       - run: npm run lint
+  cancel_merge:
+    runs-on: ubuntu-latest
+    needs: [run_checks]
+    steps:
+      - name: Cancel the merger if the checks fail
+        if: failure()
+        run: |
+          echo "Checks failed. Cancelling the merge."
+          exit 1
